apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payments-ms
  name: payments-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payments-ms
    spec:
      containers:
        - image: aguekdjian/payments-ms:latest
          name: payments-ms
          env:
            - name: PORT
              value: "3006"
            - name: NATS_URL
              value: "nats://nats"
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: payments-secrets
                  key: stripe_secret_key
            - name: STRIPE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: payments-secrets
                  key: stripe_webhook_secret
            - name: STRIPE_SUCCESS_URL
              valueFrom:
                secretKeyRef:
                  name: payments-secrets
                  key: stripe_success_url
            - name: STRIPE_CANCEL_URL
              valueFrom:
                secretKeyRef:
                  name: payments-secrets
                  key: stripe_cancel_url
          resources: {}
status: {}
