apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: payments-ms
  name: payments-ms
spec:
  ports:
  - name: "3006"
    port: 3006
    protocol: TCP
    targetPort: 3006
  selector:
    app: payments-ms
  type: NodePort
status:
  loadBalancer: {}
