version: "3"
services:
  # ====================
  # NATS Server
  # ====================
  nats-server:
    image: nats:latest

  # ====================
  #  Gateway
  # ====================
  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: Dockerfile.prod
    image: client-gateway-prod
    ports:
      - ${CLIENT_GATEWAY_PORT}:3000
    environment:
      - PORT=3000
      - NATS_URL=${NATS_URL}

  # ====================
  # Products Microservice
  # ====================
  products-ms:
    build:
      context: ./products-ms
      dockerfile: Dockerfile.prod
    image: products-ms-prod
    environment:
      - PORT=${PRODUCTS_MS_PORT}
      - NATS_URL=${NATS_URL}
      - DATABASE_URL=file:./dev.db

  # ====================
  # Orders Microservice
  # ====================
  orders-ms:
    build:
      context: ./orders-ms
      dockerfile: Dockerfile.prod
      args:
        DATABASE_URL: ${DATABASE_URL_POSTGRES_ORDERS_MS}
    image: orders-ms-prod
    environment:
      - PORT=${ORDERS_MS_PORT}
      - NATS_URL=${NATS_URL}
      - DATABASE_URL=${DATABASE_URL_POSTGRES_ORDERS_MS}

  # ====================
  # Payments Microservice
  # ====================
  payments-ms:
    build:
      context: ./payments-ms
      dockerfile: Dockerfile.prod
    image: payments-ms-prod
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_URL=${NATS_URL}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}

  # ====================
  # Auth Microservice
  # ====================
  auth-ms:
    build:
      context: ./auth-ms
      dockerfile: Dockerfile.prod
    image: auth-ms-prod
    environment:
      - PORT=${AUTH_MS_PORT}
      - NATS_URL=${NATS_URL}
      - AUTH_DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
