name: Dispatch Docker Builds

on:
  push:
    branches: [main]

jobs:
  avoid_reduncy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ github.token }}
          
  generate_docker_image:
    needs: avoid_reduncy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app-name: [auth-ms, client-gateway, product-ms, orders-ms, payments-ms]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
