name: Docker Builds

on:
  push:
    branches: [main]

jobs:
  avoid_reduncy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ github.token }}

  generate_docker_image:
    needs: avoid_reduncy
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          apps=("auth-ms" "client-gateway" "product-ms" "orders-ms" "payments-ms")
          for app in "${apps[@]}"; do
            echo "Building and pushing $app"
            ls && ls $app
            pwd
            docker build -f Dockerfile.prod -t ${{ secrets.DOCKER_USERNAME }}/$app:latest $app/.
            docker push ${{ secrets.DOCKER_USERNAME }}/$app:latest
          done
