name: Build images

on:
  push:
    branches: [main]

jobs:
  avoid_reduncy:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ github.token }}

  generate_docker_image:
    uses: ./.github/workflows/docker-build.yml
    with:
      app-name: ${{ matrix.app-name }}
    strategy:
      matrix:
        app-name: [auth-ms, client-gateway, product-ms, orders-ms, payments-ms]
