name: Build images

on:
  push:
    branches: [main]

jobs:
  avoid_reduncy:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ github.token }}

  generate_docker_image:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        app-name: [auth-ms, client-gateway, product-ms, orders-ms, payments-ms]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Call Docker build and push workflow
        uses: actions/github-script@v7.0.1
        with:
          script: |
            const github = require('@actions/github');
            await github.rest.actions.createWorkflowDispatch({
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              workflow_id: 'docker-build.yml',
              ref: github.context.ref,
              inputs: {
                'app-name': '${{ matrix.app-name }}'
              }
            });
