name: Dispatch Docker Builds

on:
  push:
    branches: [main]

jobs:
  generate_docker_image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app-name: [auth-ms, client-gateway, product-ms, orders-ms, payments-ms]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
